version: 2
jobs:
  deploy:
    docker:
      - image: circleci/java
      
    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: Install deps
          command: |
            sudo apt-get install make
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            git config --global user.name "Jack Mahoney (CircleCI)"
            git config --global user.email "jackmahoney212@gmail.com"

      - run: 
          name: Update
          command: |
            java -jar ./swagger-codegen-cli.jar generate --config ./client-config.json --lang=typescript-node -i https://api.mailslurp.com/v2/api-docs
            node shim.js
            npm install
            npm run test

      - run:
          name: Commit
          command: |
            git add -A . 
            git commit -m "deploy $CIRCLE_SHA1"
            git push -qf https://$GITHUB_TOKEN@github.com/jackmahoney/emaile2e-javascript-client.git master

      - run:
          name: Publish
          command: |
            npm publish

workflows:
  version: 2
  publish:
    jobs:
      - deploy:
          filters:
            branches:
              only: dev
