version: 2
jobs:
  deploy:
    docker:
      - image: circleci/java
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get install make
      - run: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: make deploy


workflows:
  version: 2
  publish:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
